### ISSUE TITLE
JSON parse error

### ISSUE THREAD

**Issue by JAICHANGPARK** [priyankapakhale/GoogleMapsNearbyPlacesDemo#1]
Hello .
How can I resolved this problem?

```
{ "error_message" : "Browser API keys cannot have referer restrictions when used with this API.",   "html_attributions" : [],   "results" : [],   "status" : "REQUEST_DENIED"}

```

**Comment by priyankapakhale** [comment]
You need to create your own API key and use it in the code.

**Comment by priyankapakhale** [comment]
You need to create your own API key and use it in the code. It will not allow you to use my key.

**Comment by JAICHANGPARK** [comment]
@priyankapakhale thank you I resovled
